// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdP4KxtllVBf96F1vUYWGgTpGJtbiD0zE',
    appId: '1:809778544350:web:59ae1ae91b18b8425e0c4f',
    messagingSenderId: '809778544350',
    projectId: 'ryeojeong-5a430',
    authDomain: 'ryeojeong-5a430.firebaseapp.com',
    storageBucket: 'ryeojeong-5a430.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcDeJQnzaV_oJBss9BtJjnc4WeKtcS_B4',
    appId: '1:809778544350:android:3ee2ee515585e6df5e0c4f',
    messagingSenderId: '809778544350',
    projectId: 'ryeojeong-5a430',
    storageBucket: 'ryeojeong-5a430.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAmHg1iNRm6fW7WGqrGap12-iNvowSa74',
    appId: '1:809778544350:ios:a8cf1ed0ad927a325e0c4f',
    messagingSenderId: '809778544350',
    projectId: 'ryeojeong-5a430',
    storageBucket: 'ryeojeong-5a430.firebasestorage.app',
    iosBundleId: 'com.example.re',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAmHg1iNRm6fW7WGqrGap12-iNvowSa74',
    appId: '1:809778544350:ios:a8cf1ed0ad927a325e0c4f',
    messagingSenderId: '809778544350',
    projectId: 'ryeojeong-5a430',
    storageBucket: 'ryeojeong-5a430.firebasestorage.app',
    iosBundleId: 'com.example.re',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdP4KxtllVBf96F1vUYWGgTpGJtbiD0zE',
    appId: '1:809778544350:web:851581ce356d016e5e0c4f',
    messagingSenderId: '809778544350',
    projectId: 'ryeojeong-5a430',
    authDomain: 'ryeojeong-5a430.firebaseapp.com',
    storageBucket: 'ryeojeong-5a430.firebasestorage.app',
  );
}
